// <auto-generated />
using System;
using DB;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DB.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230519131311_Add_Example_model_for_tree")]
    partial class Add_Example_model_for_tree
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0-preview.4.23259.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DB.Entities.Action", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Path")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RefAppId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Action", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2023, 5, 19, 13, 13, 11, 604, DateTimeKind.Utc).AddTicks(3554),
                            Name = "Delete",
                            Path = "",
                            RefAppId = 0,
                            Updated = new DateTime(2023, 5, 19, 13, 13, 11, 604, DateTimeKind.Utc).AddTicks(3555)
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2023, 5, 19, 13, 13, 11, 604, DateTimeKind.Utc).AddTicks(3563),
                            Name = "Edit",
                            Path = "",
                            RefAppId = 1,
                            Updated = new DateTime(2023, 5, 19, 13, 13, 11, 604, DateTimeKind.Utc).AddTicks(3564)
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTime(2023, 5, 19, 13, 13, 11, 604, DateTimeKind.Utc).AddTicks(3565),
                            Name = "Read",
                            Path = "",
                            RefAppId = 1,
                            Updated = new DateTime(2023, 5, 19, 13, 13, 11, 604, DateTimeKind.Utc).AddTicks(3565)
                        },
                        new
                        {
                            Id = 4,
                            Created = new DateTime(2023, 5, 19, 13, 13, 11, 604, DateTimeKind.Utc).AddTicks(3566),
                            Name = "Delete",
                            Path = "",
                            RefAppId = 2,
                            Updated = new DateTime(2023, 5, 19, 13, 13, 11, 604, DateTimeKind.Utc).AddTicks(3566)
                        },
                        new
                        {
                            Id = 5,
                            Created = new DateTime(2023, 5, 19, 13, 13, 11, 604, DateTimeKind.Utc).AddTicks(3567),
                            Name = "Edit",
                            Path = "",
                            RefAppId = 2,
                            Updated = new DateTime(2023, 5, 19, 13, 13, 11, 604, DateTimeKind.Utc).AddTicks(3567)
                        },
                        new
                        {
                            Id = 6,
                            Created = new DateTime(2023, 5, 19, 13, 13, 11, 604, DateTimeKind.Utc).AddTicks(3570),
                            Name = "Read",
                            Path = "",
                            RefAppId = 2,
                            Updated = new DateTime(2023, 5, 19, 13, 13, 11, 604, DateTimeKind.Utc).AddTicks(3570)
                        },
                        new
                        {
                            Id = 7,
                            Created = new DateTime(2023, 5, 19, 13, 13, 11, 604, DateTimeKind.Utc).AddTicks(3571),
                            Name = "Delete",
                            Path = "",
                            RefAppId = 3,
                            Updated = new DateTime(2023, 5, 19, 13, 13, 11, 604, DateTimeKind.Utc).AddTicks(3571)
                        },
                        new
                        {
                            Id = 8,
                            Created = new DateTime(2023, 5, 19, 13, 13, 11, 604, DateTimeKind.Utc).AddTicks(3572),
                            Name = "Edit",
                            Path = "",
                            RefAppId = 3,
                            Updated = new DateTime(2023, 5, 19, 13, 13, 11, 604, DateTimeKind.Utc).AddTicks(3572)
                        },
                        new
                        {
                            Id = 9,
                            Created = new DateTime(2023, 5, 19, 13, 13, 11, 604, DateTimeKind.Utc).AddTicks(3572),
                            Name = "Read",
                            Path = "",
                            RefAppId = 3,
                            Updated = new DateTime(2023, 5, 19, 13, 13, 11, 604, DateTimeKind.Utc).AddTicks(3573)
                        },
                        new
                        {
                            Id = 10,
                            Created = new DateTime(2023, 5, 19, 13, 13, 11, 604, DateTimeKind.Utc).AddTicks(3574),
                            Name = "Delete",
                            Path = "",
                            RefAppId = 4,
                            Updated = new DateTime(2023, 5, 19, 13, 13, 11, 604, DateTimeKind.Utc).AddTicks(3574)
                        },
                        new
                        {
                            Id = 11,
                            Created = new DateTime(2023, 5, 19, 13, 13, 11, 604, DateTimeKind.Utc).AddTicks(3575),
                            Name = "Edit",
                            Path = "",
                            RefAppId = 4,
                            Updated = new DateTime(2023, 5, 19, 13, 13, 11, 604, DateTimeKind.Utc).AddTicks(3575)
                        },
                        new
                        {
                            Id = 12,
                            Created = new DateTime(2023, 5, 19, 13, 13, 11, 604, DateTimeKind.Utc).AddTicks(3575),
                            Name = "Read",
                            Path = "",
                            RefAppId = 4,
                            Updated = new DateTime(2023, 5, 19, 13, 13, 11, 604, DateTimeKind.Utc).AddTicks(3576)
                        },
                        new
                        {
                            Id = 13,
                            Created = new DateTime(2023, 5, 19, 13, 13, 11, 604, DateTimeKind.Utc).AddTicks(3576),
                            Name = "Delete",
                            Path = "",
                            RefAppId = 5,
                            Updated = new DateTime(2023, 5, 19, 13, 13, 11, 604, DateTimeKind.Utc).AddTicks(3576)
                        },
                        new
                        {
                            Id = 14,
                            Created = new DateTime(2023, 5, 19, 13, 13, 11, 604, DateTimeKind.Utc).AddTicks(3577),
                            Name = "Edit",
                            Path = "",
                            RefAppId = 5,
                            Updated = new DateTime(2023, 5, 19, 13, 13, 11, 604, DateTimeKind.Utc).AddTicks(3577)
                        },
                        new
                        {
                            Id = 15,
                            Created = new DateTime(2023, 5, 19, 13, 13, 11, 604, DateTimeKind.Utc).AddTicks(3578),
                            Name = "Read",
                            Path = "",
                            RefAppId = 5,
                            Updated = new DateTime(2023, 5, 19, 13, 13, 11, 604, DateTimeKind.Utc).AddTicks(3578)
                        },
                        new
                        {
                            Id = 16,
                            Created = new DateTime(2023, 5, 19, 13, 13, 11, 604, DateTimeKind.Utc).AddTicks(3579),
                            Name = "Delete",
                            Path = "",
                            RefAppId = 6,
                            Updated = new DateTime(2023, 5, 19, 13, 13, 11, 604, DateTimeKind.Utc).AddTicks(3579)
                        },
                        new
                        {
                            Id = 17,
                            Created = new DateTime(2023, 5, 19, 13, 13, 11, 604, DateTimeKind.Utc).AddTicks(3579),
                            Name = "Edit",
                            Path = "",
                            RefAppId = 6,
                            Updated = new DateTime(2023, 5, 19, 13, 13, 11, 604, DateTimeKind.Utc).AddTicks(3580)
                        },
                        new
                        {
                            Id = 18,
                            Created = new DateTime(2023, 5, 19, 13, 13, 11, 604, DateTimeKind.Utc).AddTicks(3581),
                            Name = "Read",
                            Path = "",
                            RefAppId = 6,
                            Updated = new DateTime(2023, 5, 19, 13, 13, 11, 604, DateTimeKind.Utc).AddTicks(3581)
                        });
                });

            modelBuilder.Entity("DB.Entities.Application", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Application", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApplicationName = "App1",
                            Created = new DateTime(2023, 5, 19, 13, 13, 11, 604, DateTimeKind.Utc).AddTicks(9252),
                            Updated = new DateTime(2023, 5, 19, 13, 13, 11, 604, DateTimeKind.Utc).AddTicks(9252)
                        },
                        new
                        {
                            Id = 2,
                            ApplicationName = "App2",
                            Created = new DateTime(2023, 5, 19, 13, 13, 11, 604, DateTimeKind.Utc).AddTicks(9256),
                            Updated = new DateTime(2023, 5, 19, 13, 13, 11, 604, DateTimeKind.Utc).AddTicks(9257)
                        },
                        new
                        {
                            Id = 3,
                            ApplicationName = "App3",
                            Created = new DateTime(2023, 5, 19, 13, 13, 11, 604, DateTimeKind.Utc).AddTicks(9258),
                            Updated = new DateTime(2023, 5, 19, 13, 13, 11, 604, DateTimeKind.Utc).AddTicks(9258)
                        },
                        new
                        {
                            Id = 4,
                            ApplicationName = "App4",
                            Created = new DateTime(2023, 5, 19, 13, 13, 11, 604, DateTimeKind.Utc).AddTicks(9259),
                            Updated = new DateTime(2023, 5, 19, 13, 13, 11, 604, DateTimeKind.Utc).AddTicks(9259)
                        },
                        new
                        {
                            Id = 5,
                            ApplicationName = "App5",
                            Created = new DateTime(2023, 5, 19, 13, 13, 11, 604, DateTimeKind.Utc).AddTicks(9260),
                            Updated = new DateTime(2023, 5, 19, 13, 13, 11, 604, DateTimeKind.Utc).AddTicks(9260)
                        },
                        new
                        {
                            Id = 6,
                            ApplicationName = "App6",
                            Created = new DateTime(2023, 5, 19, 13, 13, 11, 604, DateTimeKind.Utc).AddTicks(9262),
                            Updated = new DateTime(2023, 5, 19, 13, 13, 11, 604, DateTimeKind.Utc).AddTicks(9263)
                        });
                });

            modelBuilder.Entity("DB.Entities.Example", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdParent")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Path")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RefAppId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Example", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2023, 5, 19, 13, 13, 11, 605, DateTimeKind.Utc).AddTicks(7131),
                            IdParent = 0,
                            Name = "Delete",
                            Path = "",
                            RefAppId = 0,
                            Updated = new DateTime(2023, 5, 19, 13, 13, 11, 605, DateTimeKind.Utc).AddTicks(7132)
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2023, 5, 19, 13, 13, 11, 605, DateTimeKind.Utc).AddTicks(7138),
                            IdParent = 1,
                            Name = "Edit",
                            Path = "",
                            RefAppId = 1,
                            Updated = new DateTime(2023, 5, 19, 13, 13, 11, 605, DateTimeKind.Utc).AddTicks(7138)
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTime(2023, 5, 19, 13, 13, 11, 605, DateTimeKind.Utc).AddTicks(7139),
                            IdParent = 2,
                            Name = "Read",
                            Path = "",
                            RefAppId = 1,
                            Updated = new DateTime(2023, 5, 19, 13, 13, 11, 605, DateTimeKind.Utc).AddTicks(7139)
                        },
                        new
                        {
                            Id = 4,
                            Created = new DateTime(2023, 5, 19, 13, 13, 11, 605, DateTimeKind.Utc).AddTicks(7140),
                            IdParent = 3,
                            Name = "Delete",
                            Path = "",
                            RefAppId = 2,
                            Updated = new DateTime(2023, 5, 19, 13, 13, 11, 605, DateTimeKind.Utc).AddTicks(7140)
                        },
                        new
                        {
                            Id = 5,
                            Created = new DateTime(2023, 5, 19, 13, 13, 11, 605, DateTimeKind.Utc).AddTicks(7141),
                            IdParent = 4,
                            Name = "Edit",
                            Path = "",
                            RefAppId = 2,
                            Updated = new DateTime(2023, 5, 19, 13, 13, 11, 605, DateTimeKind.Utc).AddTicks(7141)
                        },
                        new
                        {
                            Id = 6,
                            Created = new DateTime(2023, 5, 19, 13, 13, 11, 605, DateTimeKind.Utc).AddTicks(7143),
                            IdParent = 4,
                            Name = "Read",
                            Path = "",
                            RefAppId = 2,
                            Updated = new DateTime(2023, 5, 19, 13, 13, 11, 605, DateTimeKind.Utc).AddTicks(7143)
                        });
                });

            modelBuilder.Entity("DB.Entities.TreeView", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ApplicationTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<int>("ParentApplicationId")
                        .HasColumnType("int");

                    b.Property<int>("RefApplicationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("TreeView", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ApplicationTypeId = 1,
                            Created = new DateTime(2023, 5, 19, 13, 13, 11, 606, DateTimeKind.Utc).AddTicks(2541),
                            ParentApplicationId = 0,
                            RefApplicationId = 1,
                            Updated = new DateTime(2023, 5, 19, 13, 13, 11, 606, DateTimeKind.Utc).AddTicks(2541)
                        },
                        new
                        {
                            Id = 2,
                            ApplicationTypeId = 1,
                            Created = new DateTime(2023, 5, 19, 13, 13, 11, 606, DateTimeKind.Utc).AddTicks(2545),
                            ParentApplicationId = 0,
                            RefApplicationId = 2,
                            Updated = new DateTime(2023, 5, 19, 13, 13, 11, 606, DateTimeKind.Utc).AddTicks(2545)
                        },
                        new
                        {
                            Id = 3,
                            ApplicationTypeId = 1,
                            Created = new DateTime(2023, 5, 19, 13, 13, 11, 606, DateTimeKind.Utc).AddTicks(2547),
                            ParentApplicationId = 1,
                            RefApplicationId = 3,
                            Updated = new DateTime(2023, 5, 19, 13, 13, 11, 606, DateTimeKind.Utc).AddTicks(2547)
                        },
                        new
                        {
                            Id = 4,
                            ApplicationTypeId = 1,
                            Created = new DateTime(2023, 5, 19, 13, 13, 11, 606, DateTimeKind.Utc).AddTicks(2548),
                            ParentApplicationId = 2,
                            RefApplicationId = 4,
                            Updated = new DateTime(2023, 5, 19, 13, 13, 11, 606, DateTimeKind.Utc).AddTicks(2548)
                        },
                        new
                        {
                            Id = 5,
                            ApplicationTypeId = 1,
                            Created = new DateTime(2023, 5, 19, 13, 13, 11, 606, DateTimeKind.Utc).AddTicks(2549),
                            ParentApplicationId = 3,
                            RefApplicationId = 5,
                            Updated = new DateTime(2023, 5, 19, 13, 13, 11, 606, DateTimeKind.Utc).AddTicks(2549)
                        },
                        new
                        {
                            Id = 6,
                            ApplicationTypeId = 1,
                            Created = new DateTime(2023, 5, 19, 13, 13, 11, 606, DateTimeKind.Utc).AddTicks(2552),
                            ParentApplicationId = 5,
                            RefApplicationId = 6,
                            Updated = new DateTime(2023, 5, 19, 13, 13, 11, 606, DateTimeKind.Utc).AddTicks(2552)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
